server:
    ip: "127.0.0.1"
    port: 30000

# entrance of the tunnel.
# putty -pw i-am-password unix-user-name@192.168.10.10
router:
    name: "unix-user-name"
    password: "i-am-password"
    ip: "192.168.10.10"
    port: 22 # check is ssh default port.

# destination of the tunnel. if you using this example on inbound intranet postgres db.
destination:
  ip: "192.168.10.100"
  port: 5432